import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

import fs from "fs";
import path from "path";

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Тестовое хранилище
const vaultPath = "C:\\Users\\talyu\\Desktop\\Obsidian_OMIS";
const targetDir = `${vaultPath}\\.obsidian\\plugins\\Plagin-omis`;

const copyPluginFiles = {
    name: 'copy-plugin-files',
    setup(build) {
        build.onEnd(() => {
            if (!fs.existsSync(targetDir)) {
                fs.mkdirSync(targetDir, { recursive: true });
            }
            // Копируем main.js
            if (fs.existsSync("./main.js")) {
                fs.copyFileSync("./main.js", path.join(targetDir, "main.js"));
            }
            // Копируем manifest.json
            if (fs.existsSync("./manifest.json")) {
                fs.copyFileSync("./manifest.json", path.join(targetDir, "manifest.json"));
            }
            // Копируем styles.css, если он появится в будущем
            if (fs.existsSync("./styles.css")) {
                fs.copyFileSync("./styles.css", path.join(targetDir, "styles.css"));
            }
            // Копируем папку outlook со скриптами
            const outlookSrc = "./src/outlook";
            const outlookDest = path.join(targetDir, "outlook");
            if (fs.existsSync(outlookSrc)) {
                if (!fs.existsSync(outlookDest)) {
                    fs.mkdirSync(outlookDest, { recursive: true });
                }
                const files = fs.readdirSync(outlookSrc);
                for (const file of files) {
                    fs.copyFileSync(path.join(outlookSrc, file), path.join(outlookDest, file));
                }
            }

            console.log(`[ESBuild] Файлы плагина скопированы в: ${targetDir}`);
            console.log(`[ESBuild] Перезагрузите плагин: Settings → Community Plugins → выключить/включить Monitoring Plugin`);
        });
    },
};

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    plugins: [copyPluginFiles],
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
