/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MonitoringPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/llm/LLMService.ts
var import_obsidian = require("obsidian");
var LLMService = class {
  constructor(settings) {
    this.settings = settings;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  async summarizeIncident(content) {
    var _a, _b, _c;
    if (this.settings.useMockLLM) {
      return `**[MOCK] \u041E\u043F\u0438\u0441\u0430\u043D\u0438\u0435 \u0438\u043D\u0446\u0438\u0434\u0435\u043D\u0442\u0430:**
\u041F\u0440\u043E\u0438\u0437\u043E\u0448\u043B\u0430 \u0442\u0435\u0441\u0442\u043E\u0432\u0430\u044F \u043E\u0448\u0438\u0431\u043A\u0430. \u0421\u0438\u0441\u0442\u0435\u043C\u044B \u0440\u0430\u0431\u043E\u0442\u0430\u044E\u0442 \u0432 \u0448\u0442\u0430\u0442\u043D\u043E\u043C \u0440\u0435\u0436\u0438\u043C\u0435.

**\u0417\u0430\u0434\u0430\u0447\u0438:**
- \u041F\u0440\u043E\u0432\u0435\u0440\u0438\u0442\u044C \u043B\u043E\u0433\u0438 \u0441\u0435\u0440\u0432\u0435\u0440\u0430
- \u0421\u043E\u043E\u0431\u0449\u0438\u0442\u044C \u0434\u0435\u0436\u0443\u0440\u043D\u043E\u043C\u0443 \u0430\u0434\u043C\u0438\u043D\u0438\u0441\u0442\u0440\u0430\u0442\u043E\u0440\u0443

*\u041E\u0440\u0438\u0433\u0438\u043D\u0430\u043B\u044C\u043D\u044B\u0439 \u0442\u0435\u043A\u0441\u0442:* ${content.slice(0, 50)}...`;
    }
    if (!this.settings.llmApiKey || !this.settings.llmBaseUrl) {
      throw new Error("LLM API Not Configured in Settings!");
    }
    let baseUrl = this.settings.llmBaseUrl.replace(/\/$/, "");
    let endpoint = baseUrl;
    if (!baseUrl.endsWith("/chat/completions")) {
      if (baseUrl.match(/\/(v\d+|api\/v\d+)$/)) {
        endpoint = `${baseUrl}/chat/completions`;
      } else {
        endpoint = `${baseUrl}/v1/chat/completions`;
      }
    }
    const requestData = {
      model: this.settings.llmModel || "llm-medium-moe-instruct",
      messages: [
        { role: "system", content: "\u0422\u044B \u043A\u043E\u0440\u043F\u043E\u0440\u0430\u0442\u0438\u0432\u043D\u044B\u0439 \u0418\u0418-\u0430\u0441\u0441\u0438\u0441\u0442\u0435\u043D\u0442 \u0434\u043B\u044F \u043C\u043E\u043D\u0438\u0442\u043E\u0440\u0438\u043D\u0433\u0430 \u0438\u043D\u0446\u0438\u0434\u0435\u043D\u0442\u043E\u0432. \u041E\u0442\u0432\u0435\u0447\u0430\u0439 \u0432\u0441\u0435\u0433\u0434\u0430 \u043D\u0430 \u0440\u0443\u0441\u0441\u043A\u043E\u043C \u044F\u0437\u044B\u043A\u0435." },
        { role: "user", content: `\u0421\u0434\u0435\u043B\u0430\u0439 \u0441\u0430\u043C\u043C\u0430\u0440\u0438 (\u043A\u0440\u0430\u0442\u043A\u0443\u044E \u0432\u044B\u0436\u0438\u043C\u043A\u0443) \u0441\u043B\u0435\u0434\u0443\u044E\u0449\u0435\u0433\u043E \u0438\u043D\u0446\u0438\u0434\u0435\u043D\u0442\u0430 \u0438 \u0432\u044B\u0434\u0435\u043B\u0438 \u0437\u0430\u0434\u0430\u0447\u0438:

${content}` }
      ],
      stream: false,
      temperature: 0.7,
      max_tokens: 1500
    };
    const requestParams = {
      url: endpoint,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${this.settings.llmApiKey}`
      },
      body: JSON.stringify(requestData)
    };
    try {
      const response = await (0, import_obsidian.requestUrl)(requestParams);
      if (response.status >= 200 && response.status < 300) {
        const json = response.json;
        return ((_c = (_b = (_a = json.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content) || "No summary generated.";
      } else {
        throw new Error(`LLM Error ${response.status}: ${response.text}`);
      }
    } catch (error) {
      console.error("LLM API Error:", error);
      throw new Error(`Failed to contact LLM: ${error.message}`);
    }
  }
  async updateIncidentSummary(oldSummary, newContent) {
    var _a, _b, _c;
    if (this.settings.useMockLLM) {
      return `**[MOCK] \u041E\u0431\u043D\u043E\u0432\u043B\u0435\u043D\u043D\u0430\u044F \u0438\u043D\u0444\u043E\u0440\u043C\u0430\u0446\u0438\u044F \u043F\u043E \u0438\u043D\u0446\u0438\u0434\u0435\u043D\u0442\u0443:**

${oldSummary}

**\u041D\u043E\u0432\u043E\u0435 \u043E\u0431\u043D\u043E\u0432\u043B\u0435\u043D\u0438\u0435:**
\u041F\u043E\u043B\u0443\u0447\u0435\u043D\u044B \u043D\u043E\u0432\u044B\u0435 \u0434\u0430\u043D\u043D\u044B\u0435: ${newContent.slice(0, 50)}... \u0422\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044F \u0430\u043D\u0430\u043B\u0438\u0437.`;
    }
    if (!this.settings.llmApiKey || !this.settings.llmBaseUrl) {
      throw new Error("LLM API Not Configured in Settings!");
    }
    let baseUrl = this.settings.llmBaseUrl.replace(/\/$/, "");
    let endpoint = baseUrl;
    if (!baseUrl.endsWith("/chat/completions")) {
      if (baseUrl.match(/\/(v\d+|api\/v\d+)$/)) {
        endpoint = `${baseUrl}/chat/completions`;
      } else {
        endpoint = `${baseUrl}/v1/chat/completions`;
      }
    }
    const requestData = {
      model: this.settings.llmModel || "llm-medium-moe-instruct",
      messages: [
        { role: "system", content: "\u0422\u044B \u043A\u043E\u0440\u043F\u043E\u0440\u0430\u0442\u0438\u0432\u043D\u044B\u0439 \u0418\u0418-\u0430\u0441\u0441\u0438\u0441\u0442\u0435\u043D\u0442 \u0434\u043B\u044F \u043C\u043E\u043D\u0438\u0442\u043E\u0440\u0438\u043D\u0433\u0430 \u0438\u043D\u0446\u0438\u0434\u0435\u043D\u0442\u043E\u0432. \u041E\u0442\u0432\u0435\u0447\u0430\u0439 \u0432\u0441\u0435\u0433\u0434\u0430 \u043D\u0430 \u0440\u0443\u0441\u0441\u043A\u043E\u043C \u044F\u0437\u044B\u043A\u0435." },
        { role: "user", content: `\u0412\u043E\u0442 \u0442\u0435\u043A\u0443\u0449\u0435\u0435 \u0441\u0430\u043C\u043C\u0430\u0440\u0438 \u0438\u043D\u0446\u0438\u0434\u0435\u043D\u0442\u0430:
${oldSummary}

\u041F\u043E\u0441\u0442\u0443\u043F\u0438\u043B\u043E \u043D\u043E\u0432\u043E\u0435 \u0441\u043E\u043E\u0431\u0449\u0435\u043D\u0438\u0435 \u043F\u043E \u044D\u0442\u043E\u0439 \u043F\u0440\u043E\u0431\u043B\u0435\u043C\u0435:
${newContent}

\u041F\u043E\u0436\u0430\u043B\u0443\u0439\u0441\u0442\u0430, \u043E\u0431\u043D\u043E\u0432\u0438 \u0441\u0430\u043C\u043C\u0430\u0440\u0438 \u0438\u043D\u0446\u0438\u0434\u0435\u043D\u0442\u0430 \u0441 \u0443\u0447\u0435\u0442\u043E\u043C \u043D\u043E\u0432\u043E\u0439 \u0438\u043D\u0444\u043E\u0440\u043C\u0430\u0446\u0438\u0438 (\u043F\u0438\u0448\u0438 \u043D\u0430 \u0440\u0443\u0441\u0441\u043A\u043E\u043C \u044F\u0437\u044B\u043A\u0435).` }
      ],
      stream: false,
      temperature: 0.7,
      max_tokens: 1500
    };
    const requestParams = {
      url: endpoint,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${this.settings.llmApiKey}`
      },
      body: JSON.stringify(requestData)
    };
    try {
      const response = await (0, import_obsidian.requestUrl)(requestParams);
      if (response.status >= 200 && response.status < 300) {
        const json = response.json;
        return ((_c = (_b = (_a = json.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content) || "No summary generated.";
      } else {
        throw new Error(`LLM Error ${response.status}: ${response.text}`);
      }
    } catch (error) {
      console.error("LLM API Error:", error);
      throw new Error(`Failed to contact LLM: ${error.message}`);
    }
  }
};

// src/outlook/OutlookService.ts
var import_child_process = require("child_process");
var path = __toESM(require("path"));
var OutlookService = class {
  constructor(settings, app) {
    this.settings = settings;
    this.app = app;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  async fetchEmails() {
    if (this.settings.useMockData) {
      return [
        {
          entryId: `mock-1-${Date.now()}`,
          conversationTopic: "\u041E\u0448\u0438\u0431\u043A\u0430 \u0441\u0435\u0440\u0432\u0435\u0440\u0430 \u0411\u0414",
          subject: "\u041A\u0440\u0438\u0442\u0438\u0447\u0435\u0441\u043A\u0430\u044F \u043E\u0448\u0438\u0431\u043A\u0430: \u0441\u0435\u0440\u0432\u0435\u0440 \u0431\u0430\u0437\u044B \u0434\u0430\u043D\u043D\u044B\u0445 \u043D\u0435 \u043E\u0442\u0432\u0435\u0447\u0430\u0435\u0442",
          sender: "\u0421\u0438\u0441\u0442\u0435\u043C\u0430 \u041C\u043E\u043D\u0438\u0442\u043E\u0440\u0438\u043D\u0433\u0430 (Zabbix)",
          receivedDateTime: new Date(Date.now() - 36e5).toISOString(),
          bodyPreview: "\u0417\u0434\u0440\u0430\u0432\u0441\u0442\u0432\u0443\u0439\u0442\u0435!\n\n\u0410\u0432\u0442\u043E\u043C\u0430\u0442\u0438\u0447\u0435\u0441\u043A\u0438\u0439 \u043C\u043E\u043D\u0438\u0442\u043E\u0440\u0438\u043D\u0433 \u0437\u0430\u0444\u0438\u043A\u0441\u0438\u0440\u043E\u0432\u0430\u043B \u043D\u0435\u0434\u043E\u0441\u0442\u0443\u043F\u043D\u043E\u0441\u0442\u044C \u0441\u0435\u0440\u0432\u0435\u0440\u0430 DB-MAIN-01. \u0412\u0440\u0435\u043C\u044F \u043E\u0442\u043A\u043B\u0438\u043A\u0430 \u043F\u0440\u0435\u0432\u044B\u0448\u0430\u0435\u0442 60000\u043C\u0441. \n\n\u0421\u043B\u0443\u0436\u0431\u0430 \u0431\u044B\u043B\u0430 \u043F\u0435\u0440\u0435\u0437\u0430\u043F\u0443\u0449\u0435\u043D\u0430, \u043D\u043E \u043F\u0440\u043E\u0431\u043B\u0435\u043C\u0430 \u0441\u043E\u0445\u0440\u0430\u043D\u044F\u0435\u0442\u0441\u044F. \u0422\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044F \u0432\u043C\u0435\u0448\u0430\u0442\u0435\u043B\u044C\u0441\u0442\u0432\u043E \u0438\u043D\u0436\u0435\u043D\u0435\u0440\u0430.\n"
        },
        {
          entryId: `mock-2-${Date.now()}`,
          conversationTopic: "\u041E\u0448\u0438\u0431\u043A\u0430 \u0441\u0435\u0440\u0432\u0435\u0440\u0430 \u0411\u0414",
          subject: "Re: \u041A\u0440\u0438\u0442\u0438\u0447\u0435\u0441\u043A\u0430\u044F \u043E\u0448\u0438\u0431\u043A\u0430: \u0441\u0435\u0440\u0432\u0435\u0440 \u0431\u0430\u0437\u044B \u0434\u0430\u043D\u043D\u044B\u0445 \u043D\u0435 \u043E\u0442\u0432\u0435\u0447\u0430\u0435\u0442",
          sender: "\u0418\u0432\u0430\u043D \u0418\u0432\u0430\u043D\u043E\u0432 (DevOps)",
          receivedDateTime: new Date().toISOString(),
          bodyPreview: "\u0412\u0438\u0436\u0443 \u043F\u0440\u043E\u0431\u043B\u0435\u043C\u0443. \u0417\u0430\u0448\u0435\u043B \u043D\u0430 \u0441\u0435\u0440\u0432\u0435\u0440, \u043B\u043E\u0433 \u0437\u0430\u0431\u0438\u0442 \u0437\u0430\u043F\u0440\u043E\u0441\u0430\u043C\u0438 \u043E\u0442 \u043D\u043E\u0432\u043E\u0433\u043E \u043C\u0438\u043A\u0440\u043E\u0441\u0435\u0440\u0432\u0438\u0441\u0430 \u0430\u043D\u0430\u043B\u0438\u0442\u0438\u043A\u0438. \u0421\u0435\u0439\u0447\u0430\u0441 \u0432\u0440\u0435\u043C\u0435\u043D\u043D\u043E \u043B\u0438\u043C\u0438\u0442\u0438\u0440\u0443\u044E \u0438\u0445 \u043F\u0443\u043B \u0441\u043E\u0435\u0434\u0438\u043D\u0435\u043D\u0438\u0439, \u0447\u0442\u043E\u0431\u044B \u043E\u0441\u0432\u043E\u0431\u043E\u0434\u0438\u0442\u044C \u0440\u0435\u0441\u0443\u0440\u0441\u044B."
        },
        {
          entryId: `mock-3-${Date.now()}`,
          conversationTopic: "\u041D\u043E\u0432\u044B\u0439 \u0440\u0435\u043B\u0438\u0437 frontend",
          subject: "\u0420\u0435\u043B\u0438\u0437 1.5.0 \u0443\u0441\u043F\u0435\u0448\u043D\u043E \u0440\u0430\u0437\u0432\u0435\u0440\u043D\u0443\u0442",
          sender: "CI/CD Pipeline",
          receivedDateTime: new Date().toISOString(),
          bodyPreview: "\u0414\u0435\u043F\u043B\u043E\u0439 \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043D \u0431\u0435\u0437 \u043E\u0448\u0438\u0431\u043E\u043A. \u0412\u0441\u0435 \u043F\u043E\u0434\u044B \u043F\u043E\u0434\u043D\u044F\u043B\u0438\u0441\u044C \u0443\u0441\u043F\u0435\u0448\u043D\u043E."
        }
      ];
    }
    return new Promise((resolve, reject) => {
      const adapter = this.app.vault.adapter;
      const basePath = adapter.getBasePath();
      const pythonScriptPath = path.join(basePath, ".obsidian", "plugins", "monitoring-plugin", "outlook", "fetch_mail.py");
      const pythonCommand = `chcp 65001 >nul && python "${pythonScriptPath}" --folder "${this.settings.mailFolder}"`;
      (0, import_child_process.exec)(pythonCommand, {
        encoding: "utf-8",
        env: { ...process.env, PYTHONIOENCODING: "utf-8" }
      }, (error, stdout, stderr) => {
        if (error) {
          console.error("Exec error:", error);
          return reject(new Error("Failed to execute Outlook python script. Ensure Python is installed and win32com is available."));
        }
        if (stderr) {
          console.warn("Python stderr:", stderr);
        }
        try {
          const result = JSON.parse(stdout);
          resolve(result.value || []);
        } catch (parseError) {
          console.error("JSON Parse error:", parseError, stdout);
          reject(new Error("Invalid response format from Python script."));
        }
      });
    });
  }
};

// src/notes/TemplateManager.ts
var TemplateManager = class {
  constructor(app) {
    this.app = app;
  }
  async getIncidentNoteByTopic(topic) {
    const files = this.app.vault.getMarkdownFiles();
    for (const file of files) {
      const cache = this.app.metadataCache.getFileCache(file);
      if ((cache == null ? void 0 : cache.frontmatter) && cache.frontmatter["conversation_topic"] === topic) {
        return file;
      }
    }
    return null;
  }
  async createIncidentNote(email, summary) {
    const vault = this.app.vault;
    const topic = email.conversationTopic || email.subject || "Unknown";
    const safeTitle = topic.replace(/[\\/:"*?<>|]/g, "_").slice(0, 50);
    const filename = `Incident-${safeTitle}.md`;
    const fileContent = `---
date: ${email.receivedDateTime}
sender: "${email.sender}"
subject: "${email.subject}"
conversation_topic: "${email.conversationTopic}"
status: "Pending"
tags: [incident]
---

# ${email.conversationTopic}

## \u0422\u0435\u043A\u0443\u0449\u0435\u0435 \u0441\u0430\u043C\u043C\u0430\u0440\u0438 \u0438\u043D\u0446\u0438\u0434\u0435\u043D\u0442\u0430
${summary}

---
## \u041B\u043E\u0433 \u0441\u043E\u043E\u0431\u0449\u0435\u043D\u0438\u0439

**\u041E\u0442 \u043A\u043E\u0433\u043E:** ${email.sender}
**\u0414\u0430\u0442\u0430:** ${email.receivedDateTime}
**\u0422\u0435\u043C\u0430:** ${email.subject}
**\u0421\u043E\u043E\u0431\u0449\u0435\u043D\u0438\u0435:**
${email.bodyPreview}
`;
    let file = vault.getAbstractFileByPath(filename);
    if (file) {
      await vault.modify(file, fileContent);
      return file;
    } else {
      return vault.create(filename, fileContent);
    }
  }
  async updateIncidentNote(file, email, newSummary) {
    let content = await this.app.vault.read(file);
    const summaryRegex = /## Текущее саммари инцидента\n([\s\S]*?)\n---/m;
    if (summaryRegex.test(content)) {
      content = content.replace(summaryRegex, `## \u0422\u0435\u043A\u0443\u0449\u0435\u0435 \u0441\u0430\u043C\u043C\u0430\u0440\u0438 \u0438\u043D\u0446\u0438\u0434\u0435\u043D\u0442\u0430
${newSummary}

---`);
    } else {
      content += `

## \u041D\u043E\u0432\u043E\u0435 \u0441\u0430\u043C\u043C\u0430\u0440\u0438:
${newSummary}`;
    }
    const newLogEntry = `
**\u041E\u0442 \u043A\u043E\u0433\u043E:** ${email.sender}
**\u0414\u0430\u0442\u0430:** ${email.receivedDateTime}
**\u0422\u0435\u043C\u0430:** ${email.subject}
**\u0421\u043E\u043E\u0431\u0449\u0435\u043D\u0438\u0435:**
${email.bodyPreview}
---`;
    content += newLogEntry;
    await this.app.vault.modify(file, content);
  }
  async readNoteContent(file) {
    return await this.app.vault.read(file);
  }
};

// src/settings/SettingsTab.ts
var import_obsidian2 = require("obsidian");
var DEFAULT_SETTINGS = {
  llmApiKey: "",
  llmBaseUrl: "https://api.ai.beeline.ru/api/v3",
  llmModel: "llm-medium-moe-instruct",
  mailFolder: "Inbox",
  pollInterval: 15,
  scannedEmailIds: [],
  dashboardNoteName: "Dashboard.md",
  useMockData: false,
  useMockLLM: false
};
var MonitoringSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Monitoring Plugin Settings" });
    new import_obsidian2.Setting(containerEl).setName("LLM Base URL").setDesc("Base URL for the Corporate LLM API (OpenAI Compatible)").addText((text) => text.setPlaceholder("https://api.ai.beeline.ru/api/v3").setValue(this.plugin.settings.llmBaseUrl).onChange(async (value) => {
      this.plugin.settings.llmBaseUrl = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("LLM API Key").setDesc("Bearer token for the corporate LLM API").addText((text) => {
      text.setPlaceholder("Enter your API Key").setValue(this.plugin.settings.llmApiKey).onChange(async (value) => {
        this.plugin.settings.llmApiKey = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.type = "password";
      return text;
    });
    new import_obsidian2.Setting(containerEl).setName("LLM Model").setDesc("Model name to use for summarization").addText((text) => text.setPlaceholder("llm-medium-moe-instruct").setValue(this.plugin.settings.llmModel).onChange(async (value) => {
      this.plugin.settings.llmModel = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Outlook Integration" });
    new import_obsidian2.Setting(containerEl).setName("Outlook Folder Name").setDesc("The folder to check for new incident emails (e.g. Inbox, Alerts)").addText((text) => text.setPlaceholder("Inbox").setValue(this.plugin.settings.mailFolder).onChange(async (value) => {
      this.plugin.settings.mailFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Dashboard Note Name").setDesc("Name of the note containing tracked subjects (e.g. Dashboard.md)").addText((text) => text.setPlaceholder("Dashboard.md").setValue(this.plugin.settings.dashboardNoteName).onChange(async (value) => {
      this.plugin.settings.dashboardNoteName = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Clear Scanned Emails Cache").setDesc("Reset the list of already processed emails so they can be scanned again.").addButton((button) => button.setButtonText("Clear Cache").onClick(async () => {
      this.plugin.settings.scannedEmailIds = [];
      await this.plugin.saveSettings();
      new import_obsidian2.Notice("Scanned emails cache cleared!");
    }));
    containerEl.createEl("h3", { text: "Development / Testing" });
    new import_obsidian2.Setting(containerEl).setName("Use Mock Email Data").setDesc("Inject fake Outlook emails for local testing without Outlook installed.").addToggle((toggle) => toggle.setValue(this.plugin.settings.useMockData).onChange(async (value) => {
      this.plugin.settings.useMockData = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Use Mock LLM").setDesc("Return dummy text instead of calling the corporate LLM.").addToggle((toggle) => toggle.setValue(this.plugin.settings.useMockLLM).onChange(async (value) => {
      this.plugin.settings.useMockLLM = value;
      await this.plugin.saveSettings();
    }));
  }
};

// src/main.ts
var MonitoringPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.llmService = new LLMService(this.settings);
    this.outlookService = new OutlookService(this.settings, this.app);
    this.templateManager = new TemplateManager(this.app);
    this.addRibbonIcon("mail", "\u0418\u043C\u043F\u043E\u0440\u0442\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u043F\u043E\u0447\u0442\u0443", async (evt) => {
      await this.processEmails();
    });
    this.addCommand({
      id: "import-mail",
      name: "\u041E\u0431\u043D\u043E\u0432\u0438\u0442\u044C \u043F\u043E\u0447\u0442\u0443 (Import Mail)",
      callback: async () => {
        await this.processEmails();
      }
    });
    this.addSettingTab(new MonitoringSettingTab(this.app, this));
  }
  async processEmails() {
    new import_obsidian3.Notice("\u0417\u0430\u043F\u0443\u0441\u043A \u0441\u043A\u0430\u043D\u0438\u0440\u043E\u0432\u0430\u043D\u0438\u044F \u043F\u043E\u0447\u0442\u044B...");
    try {
      const allEmails = await this.outlookService.fetchEmails();
      allEmails.reverse();
      let newEmails = allEmails.filter((e) => !this.settings.scannedEmailIds.includes(e.entryId));
      if (newEmails.length === 0) {
        new import_obsidian3.Notice("\u041D\u0435\u0442 \u043D\u043E\u0432\u044B\u0445 \u043F\u0438\u0441\u0435\u043C. \u0411\u0435\u0440\u0435\u043C \u043F\u043E\u0441\u043B\u0435\u0434\u043D\u0438\u0435 10 \u0434\u043B\u044F \u0430\u043D\u0430\u043B\u0438\u0437\u0430...");
        newEmails = allEmails.slice(Math.max(allEmails.length - 10, 0));
      }
      if (newEmails.length === 0) {
        new import_obsidian3.Notice("\u041F\u0430\u043F\u043A\u0430 \u043F\u0443\u0441\u0442\u0430.");
        return;
      }
      const dashboardFn = this.settings.dashboardNoteName;
      let trackedSubjects = [];
      const dashboardFile = this.app.vault.getAbstractFileByPath(dashboardFn);
      if (dashboardFile) {
        const cache = this.app.metadataCache.getFileCache(dashboardFile);
        if ((cache == null ? void 0 : cache.frontmatter) && Array.isArray(cache.frontmatter["tracked_subjects"])) {
          trackedSubjects = cache.frontmatter["tracked_subjects"].map((s) => s.toLowerCase());
        }
      } else {
        console.warn("Dashboard note not found, will not filter by tracked subjects.");
      }
      let processedCount = 0;
      for (const email of newEmails) {
        if (trackedSubjects.length > 0) {
          const topicLower = email.conversationTopic.toLowerCase();
          const isTracked = trackedSubjects.some((ts) => topicLower.includes(ts));
          if (!isTracked)
            continue;
        }
        const existingNote = await this.templateManager.getIncidentNoteByTopic(email.conversationTopic);
        if (existingNote) {
          new import_obsidian3.Notice(`\u041E\u0431\u043D\u043E\u0432\u043B\u044F\u0435\u043C \u0438\u043D\u0446\u0438\u0434\u0435\u043D\u0442: ${email.conversationTopic}`);
          const content = await this.templateManager.readNoteContent(existingNote);
          const summaryRegex = /## Текущее саммари инцидента\n([\s\S]*?)\n---/m;
          const match = content.match(summaryRegex);
          const oldSummary = match ? match[1].trim() : "\u041B\u043E\u0433\u043E\u0432 \u043D\u0435\u0442.";
          const combinedSummary = await this.llmService.updateIncidentSummary(oldSummary, email.bodyPreview);
          await this.templateManager.updateIncidentNote(existingNote, email, combinedSummary);
        } else {
          new import_obsidian3.Notice(`\u041D\u043E\u0432\u044B\u0439 \u0438\u043D\u0446\u0438\u0434\u0435\u043D\u0442: ${email.conversationTopic}`);
          const summary = await this.llmService.summarizeIncident(email.bodyPreview);
          await this.templateManager.createIncidentNote(email, summary);
        }
        processedCount++;
        if (!this.settings.scannedEmailIds.includes(email.entryId)) {
          this.settings.scannedEmailIds.push(email.entryId);
        }
      }
      await this.saveSettings();
      if (processedCount === 0) {
        new import_obsidian3.Notice("\u041D\u0435\u0442 \u043F\u0438\u0441\u0435\u043C \u043F\u043E \u043E\u0442\u0441\u043B\u0435\u0436\u0438\u0432\u0430\u0435\u043C\u044B\u043C \u0442\u0435\u043C\u0430\u043C.");
      } else {
        new import_obsidian3.Notice(`\u0413\u043E\u0442\u043E\u0432\u043E! \u041E\u0431\u0440\u0430\u0431\u043E\u0442\u0430\u043D\u043E \u043F\u0438\u0441\u0435\u043C: ${processedCount}`);
      }
    } catch (error) {
      console.error(error);
      new import_obsidian3.Notice("\u041E\u0448\u0438\u0431\u043A\u0430 \u043F\u0440\u0438 \u0438\u043C\u043F\u043E\u0440\u0442\u0435: " + error.message);
    }
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.llmService.updateSettings(this.settings);
    this.outlookService.updateSettings(this.settings);
  }
};
